language: node_js
node_js:
  - '4'
  - '5'
  - '6'
before_script:
  - npm install -g npm
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
script: gulp coverage
branches:
  only:
    - master
after_script:
  - gulp report-coverage
  - gulp report-codacy
env:
  global:
    secure: iZiEJXBp2fblZJC+9ijxDEZveYLEu4NfO6Fe5ye6oLOXAaPi1vAaRBUmt7mdq/NMEDGWZTSlAyLwNPxKsP96RWQOnrK8/uAE5VA07eM1w6cxwBjHtCaXgp4heQGozrmknuQTbt+88DfdJvnPSnXAwCgnKpHI0cw+jKzFzGNkssA=