language: node_js
node_js:
  - io.js
  - '0.12'
  - '0.10'
before_script:
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
script: npm run-script coveralls
only:
  - master
after_script:
  - codeclimate < ./coverage/lcov.info
env:
  global:
    secure: iZiEJXBp2fblZJC+9ijxDEZveYLEu4NfO6Fe5ye6oLOXAaPi1vAaRBUmt7mdq/NMEDGWZTSlAyLwNPxKsP96RWQOnrK8/uAE5VA07eM1w6cxwBjHtCaXgp4heQGozrmknuQTbt+88DfdJvnPSnXAwCgnKpHI0cw+jKzFzGNkssA=